In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.datasets as ds

In [96]:
X, y = ds.make_regression(n_samples=1000,n_features=4,noise=10,random_state=23)
X = X.T

In [97]:
y

array([ 7.35228601e+01, -9.39847831e+01, -8.73606782e+01,  1.92821290e+01,
        1.63438358e+01, -3.53289091e+01, -6.16770549e+01, -3.41061304e+01,
        5.21396613e-01, -7.98527800e+01, -3.07725556e+01,  2.40527243e+00,
       -5.01130918e+01,  7.92266481e+01, -4.90467448e+01,  1.87634578e+01,
        5.10042753e+01,  5.76595926e+01, -6.06952927e+01, -5.09081777e+01,
        4.35503643e+01, -2.78616499e+01, -4.21670099e+01, -1.29940964e+01,
       -7.41268177e+01,  1.93107916e+01,  3.15176752e+01,  7.96576595e-01,
       -9.12778663e+01, -9.81100620e-01,  9.02445631e+01, -3.49304812e+00,
        6.56191564e+00,  1.77159250e+01,  4.62915427e+01, -5.75279217e+01,
        9.59219106e+01, -2.66703872e+00,  4.32523554e+01,  5.97638929e+01,
        3.45803062e+01,  1.81604048e+01,  5.58383702e+01, -5.69156530e+01,
        9.40725494e+01, -3.80706172e+01, -6.17373088e+01,  1.08451990e+02,
       -8.74420808e+01, -1.40195462e+01, -3.32243071e+01,  6.10419900e+01,
        4.46924503e+01,  

In [71]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

In [98]:
y_std = calc_std_feat(y)

In [99]:
y = np.array([(1 if (a>=0) else 0) for a in y_std])

In [128]:
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,

1*. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [132]:
def calc_logloss(y, y_pred):
    y_pred = np.array([(a if ((a!=0) or (a!=1)) else np.abs(a - 1e-8)) for a in y_pred]) #Хотя вообще так делать не следует -_-
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [29]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [ ]:
### Logistic Regression

In [101]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X.T, y)
model.predict(X.T)

array([ 0.99380386, -0.04249881, -0.01984444,  0.78273322,  0.5879121 ,
        0.14152607,  0.24637961,  0.28409528,  0.71322271, -0.14216456,
        0.28097935,  0.68497217,  0.12159332,  1.01606878,  0.18232085,
        0.68103298,  0.96153499,  0.86230495,  0.15513346,  0.1599562 ,
        0.89937086,  0.33889687,  0.28601536,  0.32996493,  0.00223208,
        0.62672735,  0.77569947,  0.61641827, -0.17911108,  0.50089039,
        1.14390454,  0.55478637,  0.551109  ,  0.67994926,  0.93268711,
       -0.01907028,  1.25845656,  0.54967524,  0.78151502,  0.89411849,
        0.81088347,  0.80242582,  0.84209011,  0.03630328,  1.24919777,
        0.21934034,  0.19462722,  1.2740977 , -0.12682614,  0.52127876,
        0.25966953,  0.90016359,  0.90459298,  0.79321391,  0.88379009,
        0.60511895,  1.23496609, -0.00326131,  0.49277385, -0.31401026,
        0.43535149,  0.42629712,  0.32282059,  0.72632736,  0.43298413,
       -0.14958352,  0.04833846,  0.66123351,  1.00473499,  0.64

2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [64]:
def eval_model(X, y, iterations, alpha=1e-4, metric: callable = None):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [133]:
W = eval_model(X, y, iterations=30000, alpha=1e-1)

3000 [2.97219271 5.41758931 1.55168659 2.05499806] 0.16280463017144886
6000 [3.40776857 6.19385438 1.77379042 2.35642561] 0.15945287565372573
9000 [3.59362742 6.52289762 1.86818687 2.48427826] 0.15886546509510824
12000 [3.68394377 6.68237329 1.91400412 2.54625078] 0.15872847897365683
15000 [3.73012819 6.7638227  1.93742215 2.57790302] 0.15869285206956957
18000 [3.75431345 6.80644867 1.94968266 2.59446812] 0.15868310782271972
21000 [3.76713013 6.82903053 1.95617924 2.60324381] 0.1586803749617019
24000 [3.77396418 6.84106947 1.95964311 2.60792234] 0.15867959850256347
27000 [3.77762005 6.84750911 1.96149605 2.6104249 ] 0.15867937638484483
30000 [3.77957913 6.85095978 1.96248898 2.61176588] 0.1586793126140119


In [104]:
W

array([3.77957913, 6.85095978, 1.96248898, 2.61176588])

3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [105]:
def calc_pred_proba(W,X):
    z = np.dot(X.T, W)
    y_pred_proba = sigmoid(z)
    return y_pred_proba

In [106]:
calc_pred_proba(W,X)

array([9.99949530e-01, 6.59148182e-06, 1.20095295e-05, 9.95061150e-01,
       7.52426712e-01, 3.06427677e-04, 2.32809836e-03, 7.25490897e-03,
       9.75873665e-01, 5.13341582e-07, 5.97920167e-03, 9.38039575e-01,
       1.61371592e-04, 9.99966820e-01, 8.20068877e-04, 9.46502307e-01,
       9.99877063e-01, 9.99011641e-01, 3.35260737e-04, 5.92625534e-04,
       9.99638392e-01, 1.73681120e-02, 6.61710291e-03, 1.65583765e-02,
       1.84178244e-05, 8.93024852e-01, 9.93751656e-01, 8.61754168e-01,
       4.12821087e-07, 3.05069490e-01, 9.99997306e-01, 5.71151605e-01,
       6.12433217e-01, 9.55724749e-01, 9.99688400e-01, 1.08819935e-05,
       9.99999713e-01, 5.70418573e-01, 9.94085376e-01, 9.99460747e-01,
       9.96581860e-01, 9.94701456e-01, 9.98269341e-01, 3.60819283e-05,
       9.99999637e-01, 1.37314264e-03, 7.20171326e-04, 9.99999798e-01,
       1.27190903e-06, 3.76883441e-01, 3.45574037e-03, 9.99453996e-01,
       9.99405713e-01, 9.93654870e-01, 9.99465385e-01, 8.11387540e-01,
      

4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [109]:
def calc_pred(W,X):
    thresh = 0.5
    z = np.dot(X.T, W)
    y_pred = sigmoid(z) - thresh
    class_pred = np.array([(1 if (a>=0) else 0) for a in y_pred])
    return class_pred

In [110]:
y_pred = calc_pred(W,X)

In [111]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,

5. Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [57]:
import sklearn.metrics as metrics

In [112]:
metrics.confusion_matrix(y, y_pred)

array([[493,  15],
       [ 50, 442]], dtype=int64)

In [113]:
metrics.accuracy_score(y, y_pred)

0.935

In [116]:
metrics.precision_score(y, y_pred)

0.9671772428884027

In [114]:
metrics.recall_score(y, y_pred)

0.8983739837398373

In [115]:
metrics.f1_score(y, y_pred)

0.9315068493150684

6. Могла ли модель переобучиться? Почему?

Могла. Потому что любая модель может переобучиться. Но "переобучение" - понятие относительное (относительно генеральной совокупности данных, на которых будет применяться модель), а поскольку проверочных данных у нас нет - определённо судить о переобучении здесь невозможно.

7*. Создайте функции eval_model_l1 и eval_model_l2 с применением L1 и L2 регуляризаций соответственно.

In [117]:
def eval_model_l1(X, y, iterations, alpha=1e-4, lambda_=1e-6, metric: callable = None):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred) + lambda_ * np.sum(np.abs(W))
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [121]:
W = eval_model_l1(X, y, iterations=30000, alpha=1e-1, lambda_=1e-3)

3000 [2.97219271 5.41758931 1.55168659 2.05499806] 0.17480016910184412
6000 [3.40776857 6.19385438 1.77379042 2.35642561] 0.17318436052112277
9000 [3.59362742 6.52289762 1.86818687 2.48427826] 0.1733342897516784
12000 [3.68394377 6.68237329 1.91400412 2.54625078] 0.173554967752116
15000 [3.73012819 6.7638227  1.93742215 2.57790302] 0.17370208492575254
18000 [3.75431345 6.80644867 1.94968266 2.59446812] 0.17378799793237207
21000 [3.76713013 6.82903053 1.95617924 2.60324381] 0.17383594654906181
24000 [3.77396418 6.84106947 1.95964311 2.60792234] 0.17386219113194504
27000 [3.77762005 6.84750911 1.96149605 2.6104249 ] 0.17387642302553952
30000 [3.77957913 6.85095978 1.96248898 2.61176588] 0.17388410452475178


In [119]:
def eval_model_l2(X, y, iterations, alpha=1e-4, lambda_=1e-6, metric: callable = None):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T)) + lambda_ * np.sum(W**2)
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [123]:
W = eval_model_l2(X, y, iterations=30000, alpha=1e-1, lambda_=1e-4)

3000 [1.70700801 3.2527876  0.81361411 1.12379054] 0.20210593189622822
6000 [1.70713238 3.25306458 0.81365451 1.12386459] 0.20209795359073407
9000 [1.7071324  3.25306462 0.81365452 1.1238646 ] 0.20209795230766617
12000 [1.7071324  3.25306462 0.81365452 1.1238646 ] 0.20209795230746222
15000 [1.7071324  3.25306462 0.81365452 1.1238646 ] 0.20209795230746222
18000 [1.7071324  3.25306462 0.81365452 1.1238646 ] 0.20209795230746222
21000 [1.7071324  3.25306462 0.81365452 1.1238646 ] 0.20209795230746222
24000 [1.7071324  3.25306462 0.81365452 1.1238646 ] 0.20209795230746222
27000 [1.7071324  3.25306462 0.81365452 1.1238646 ] 0.20209795230746222
30000 [1.7071324  3.25306462 0.81365452 1.1238646 ] 0.20209795230746222
